### PR TITLE
Wr/data fix

### PR DESCRIPTION
**Pull request by WillieRuemmele**
### What does this PR do?
Adds the `--perflog` flag to `query`
uses OCLIFs builtin `dependsOn` attribute to handle flag logic
adds the `/schema` dir to the built package

### What issues does this PR fix or reference?
@W-8847778@
@W-8847723@
@W-8849875@

### CODE REVIEW

**Review by peternhale — APPROVED** [review]
Any tests that need to be added due to addition of `--perflog` flag, or is all that handled elsewhere?

**Comment by WillieRuemmele** [comment]
@peternhale it's all handled within `DataCommand` it matches the `data:record` commands now - so all the logic is identical

**Review by mshanemc — APPROVED** [review]
great use of oclif flags on the filepath stuff!
nice to see soql:query inheriting all the stuff done in DataCommand, too.

**Comment by mshanemc** [comment]
qa notes:
✅ --perflog requires json as expected on soql:query
✅ --perflog and --json produces good results on soql:query
✅ --perflog and --json produces good results on record:get
schema looks like it'll be included.  will have to merge to publish a package to know for sure.

**Pull request merged**
